<?php

/**
 * List of all supported languages with their codes and names
 * Used for language selection in the admin panel
 */
return [
    'af' => ['name' => 'Afrikaans', 'native_name' => 'Afrikaans'],
    'sq' => ['name' => 'Albanian', 'native_name' => 'Shqip'],
    'aa' => ['name' => 'Afar', 'native_name' => 'Afar'],
    'am' => ['name' => 'Amharic', 'native_name' => 'አማርኛ'],
    'ar' => ['name' => 'Arabic', 'native_name' => 'العربية'],
    'an' => ['name' => 'Aragonese', 'native_name' => 'Aragonés'],
    'hy' => ['name' => 'Armenian', 'native_name' => 'Հայերեն'],
    'as' => ['name' => 'Assamese', 'native_name' => 'অসমীয়া'],
    'ay' => ['name' => 'Aymara', 'native_name' => 'Aymar aru'],
    'az' => ['name' => 'Azerbaijani', 'native_name' => 'Azərbaycanca'],
    'ba' => ['name' => 'Bashkir', 'native_name' => 'Башҡортса'],
    'eu' => ['name' => 'Basque', 'native_name' => 'Euskera'],
    'bn' => ['name' => 'Bengali', 'native_name' => 'বাংলা'],
    'dz' => ['name' => 'Dzongkha', 'native_name' => 'རྫོང་ཁ'],
    'bh' => ['name' => 'Bihari', 'native_name' => 'भोजपुरी'],
    'bi' => ['name' => 'Bislama', 'native_name' => 'Bislama'],
    'bs' => ['name' => 'Bosnian', 'native_name' => 'Bosanski'],
    'br' => ['name' => 'Breton', 'native_name' => 'Brezhoneg'],
    'bg' => ['name' => 'Bulgarian', 'native_name' => 'Български'],
    'my' => ['name' => 'Burmese', 'native_name' => ' Myanmar'],
    'be' => ['name' => 'Belarusian', 'native_name' => 'Беларуская'],
    'km' => ['name' => 'Cambodian', 'native_name' => 'ខ្មែរ'],
    'ca' => ['name' => 'Catalan', 'native_name' => 'Català'],
    'zh' => ['name' => 'Chinese', 'native_name' => '中文'],
    'zh-CN' => ['name' => 'Chinese (Simplified)', 'native_name' => '简体中文'],
    'zh-TW' => ['name' => 'Chinese (Traditional)', 'native_name' => '繁體中文'],
    'co' => ['name' => 'Corsican', 'native_name' => 'Corsu'],
    'hr' => ['name' => 'Croatian', 'native_name' => 'Hrvatski'],
    'cs' => ['name' => 'Czech', 'native_name' => 'Čeština'],
    'da' => ['name' => 'Danish', 'native_name' => 'Dansk'],
    'nl' => ['name' => 'Dutch', 'native_name' => 'Nederlands'],
    'en' => ['name' => 'English', 'native_name' => 'English'],
    'en-GB' => ['name' => 'English (British)', 'native_name' => 'English (British)'],
    'en-US' => ['name' => 'English (American)', 'native_name' => 'English (American)'],
    'eo' => ['name' => 'Esperanto', 'native_name' => 'Esperanto'],
    'et' => ['name' => 'Estonian', 'native_name' => 'Eesti'],
    'fo' => ['name' => 'Faroese', 'native_name' => 'Føroyskt'],
    'fj' => ['name' => 'Fijian', 'native_name' => 'Vosa Vakaviti'],
    'fi' => ['name' => 'Finnish', 'native_name' => 'Suomi'],
    'fr' => ['name' => 'French', 'native_name' => 'Français'],
    'fy' => ['name' => 'Frisian', 'native_name' => 'Frysk'],
    'gd' => ['name' => 'Gaelic', 'native_name' => 'Gàidhlig'],
    'gl' => ['name' => 'Galician', 'native_name' => 'Galego'],
    'ka' => ['name' => 'Georgian', 'native_name' => 'ქართული'],
    'de' => ['name' => 'German', 'native_name' => 'Deutsch'],
    'el' => ['name' => 'Greek', 'native_name' => 'Ελληνικά'],
    'gn' => ['name' => 'Guarani', 'native_name' => 'Guaraní'],
    'gu' => ['name' => 'Gujarati', 'native_name' => 'ગુજરાતી'],
    'ha' => ['name' => 'Hausa', 'native_name' => 'Hausa'],
    'iw' => ['name' => 'Hebrew', 'native_name' => 'עברית'],
    'hi' => ['name' => 'Hindi', 'native_name' => 'हिन्दी'],
    'hu' => ['name' => 'Hungarian', 'native_name' => 'Magyar'],
    'is' => ['name' => 'Icelandic', 'native_name' => 'Íslenska'],
    'ig' => ['name' => 'Igbo', 'native_name' => 'Igbo'],
    'id' => ['name' => 'Indonesian', 'native_name' => 'Bahasa Indonesia'],
    'ia' => ['name' => 'Interlingua', 'native_name' => 'Interlingua'],
    'ie' => ['name' => 'Interlingue', 'native_name' => 'Interlingue'],
    'iu' => ['name' => 'Inuktitut', 'native_name' => 'Inuktitut'],
    'ik' => ['name' => 'Inupiak', 'native_name' => 'Inupiak'],
    'ga' => ['name' => 'Irish', 'native_name' => 'Gaeilge'],
    'it' => ['name' => 'Italian', 'native_name' => 'Italiano'],
    'ja' => ['name' => 'Japanese', 'native_name' => '日本語'],
    'jw' => ['name' => 'Javanese', 'native_name' => 'Basa Jawa'],
    'kn' => ['name' => 'Kannada', 'native_name' => 'ಕನ್ನಡ'],
    'ks' => ['name' => 'Kashmiri', 'native_name' => 'کشمیری'],
    'kk' => ['name' => 'Kazakh', 'native_name' => 'Қазақ'],
    'rw' => ['name' => 'Kinyarwanda', 'native_name' => 'Kinyarwanda'],
    'ky' => ['name' => 'Kirghiz', 'native_name' => 'Кыргызча'],
    'rn' => ['name' => 'Kirundi', 'native_name' => 'Kirundi'],
    'ko' => ['name' => 'Korean', 'native_name' => '한국어'],
    'ku' => ['name' => 'Kurdish', 'native_name' => 'کوردی'],
    'lo' => ['name' => 'Laothian', 'native_name' => 'ລາວ'],
    'la' => ['name' => 'Latin', 'native_name' => 'Latina'],
    'lv' => ['name' => 'Latvian', 'native_name' => 'Latviešu'],
    'ln' => ['name' => 'Lingala', 'native_name' => 'Lingala'],
    'lt' => ['name' => 'Lithuanian', 'native_name' => 'Lietuvių'],
    'lb' => ['name' => 'Luxembourgish', 'native_name' => 'Lëtzebuergesch'],
    'mk' => ['name' => 'Macedonian', 'native_name' => 'Македонски'],
    'mg' => ['name' => 'Malagasy', 'native_name' => 'Malagasy'],
    'ms' => ['name' => 'Malay', 'native_name' => 'Bahasa Melayu'],
    'ml' => ['name' => 'Malayalam', 'native_name' => 'മലയാളം'],
    'mt' => ['name' => 'Maltese', 'native_name' => 'Malti'],
    'mi' => ['name' => 'Maori', 'native_name' => 'Reo Māori'],
    'mr' => ['name' => 'Marathi', 'native_name' => 'मराठी'],
    'mn' => ['name' => 'Mongolian', 'native_name' => 'Монгол'],
    'ne' => ['name' => 'Nepali', 'native_name' => 'नेपाली'],
    'no' => ['name' => 'Norwegian', 'native_name' => 'Norsk'],
    'oc' => ['name' => 'Occitan', 'native_name' => 'Occitan'],
    'or' => ['name' => 'Oriya', 'native_name' => 'ଓଡ଼ିଆ'],
    'om' => ['name' => 'Oromo', 'native_name' => 'Afan Oromo'],
    'ps' => ['name' => 'Pashto', 'native_name' => 'پښتو'],
    'fa' => ['name' => 'Persian', 'native_name' => 'فارسی'],
    'pl' => ['name' => 'Polish', 'native_name' => 'Polski'],
    'pt' => ['name' => 'Portuguese', 'native_name' => 'Português'],
    'pt-BR' => ['name' => 'Portuguese (Brazilian)', 'native_name' => 'Português (Brasil)'],
    'pa' => ['name' => 'Punjabi', 'native_name' => 'ਪੰਜਾਬੀ'],
    'qu' => ['name' => 'Quechua', 'native_name' => 'Quechua'],
    'ro' => ['name' => 'Romanian', 'native_name' => 'Română'],
    'rm' => ['name' => 'Romansh', 'native_name' => 'Romansh'],
    'ru' => ['name' => 'Russian', 'native_name' => 'Русский'],
    'sm' => ['name' => 'Samoan', 'native_name' => 'Samoa'],
    'sg' => ['name' => 'Sango', 'native_name' => 'Sango'],
    'sa' => ['name' => 'Sanskrit', 'native_name' => 'संस्कृत'],
    'sr' => ['name' => 'Serbian', 'native_name' => 'Српски'],
    'sh' => ['name' => 'Serbo-Croatian', 'native_name' => 'Serbo-Croatian'],
    'st' => ['name' => 'Sesotho', 'native_name' => 'Sesotho'],
    'tn' => ['name' => 'Setswana', 'native_name' => 'Setswana'],
    'sn' => ['name' => 'Shona', 'native_name' => 'Shona'],
    'ii' => ['name' => 'Sichuan Yi', 'native_name' => 'ꆈꌠꉙ'],
    'sd' => ['name' => 'Sindhi', 'native_name' => 'سنڌي'],
    'si' => ['name' => 'Sinhala', 'native_name' => 'සිංහල'],
    'ss' => ['name' => 'Siswati', 'native_name' => 'Siswati'],
    'sk' => ['name' => 'Slovak', 'native_name' => 'Slovenčina'],
    'sl' => ['name' => 'Slovenian', 'native_name' => 'Slovenščina'],
    'so' => ['name' => 'Somali', 'native_name' => 'Soomaali'],
    'es' => ['name' => 'Spanish', 'native_name' => 'Español'],
    'su' => ['name' => 'Sundanese', 'native_name' => 'Basa Sundanese'],
    'sw' => ['name' => 'Swahili', 'native_name' => 'Kiswahili'],
    'sv' => ['name' => 'Swedish', 'native_name' => 'Svenska'],
    'tl' => ['name' => 'Tagalog', 'native_name' => 'Tagalog'],
    'tg' => ['name' => 'Tajik', 'native_name' => 'Тоҷикӣ'],
    'ta' => ['name' => 'Tamil', 'native_name' => 'தமிழ்'],
    'tt' => ['name' => 'Tatars', 'native_name' => 'Татар'],
    'te' => ['name' => 'Telugu', 'native_name' => 'తెలుగు'],
    'th' => ['name' => 'Thai', 'native_name' => 'ไทย'],
    'bo' => ['name' => 'Tibetan', 'native_name' => 'བོད་ཡིག'],
    'ti' => ['name' => 'Tigrinya', 'native_name' => 'ትግርኛ'],
    'to' => ['name' => 'Tonga', 'native_name' => 'Tonga'],
    'ts' => ['name' => 'Tsonga', 'native_name' => 'Xitsonga'],
    'tr' => ['name' => 'Turkish', 'native_name' => 'Türkçe'],
    'tk' => ['name' => 'Turkmen', 'native_name' => 'Türkmençe'],
    'tw' => ['name' => 'Twi', 'native_name' => 'Twi'],
    'ug' => ['name' => 'Uighur', 'native_name' => 'ئۇيغۇرچە'],
    'uk' => ['name' => 'Ukrainian', 'native_name' => 'Українська'],
    'ur' => ['name' => 'Urdu', 'native_name' => 'اردو'],
    'uz' => ['name' => 'Uzbek', 'native_name' => 'O\'zbekcha'],
    'vi' => ['name' => 'Vietnamese', 'native_name' => 'Tiếng Việt'],
    'vo' => ['name' => 'Volapük', 'native_name' => 'Volapük'],
    'wa' => ['name' => 'Walloon', 'native_name' => 'Walon'],
    'cy' => ['name' => 'Welsh', 'native_name' => 'Cymraeg'],
    'wo' => ['name' => 'Wolof', 'native_name' => 'Wollof'],
    'xh' => ['name' => 'Xhosa', 'native_name' => 'isiXhosa'],
    'ji' => ['name' => 'Yiddish', 'native_name' => 'ייִדיש'],
    'yo' => ['name' => 'Yoruba', 'native_name' => 'Yoruba'],
    'zu' => ['name' => 'Zulu', 'native_name' => 'isiZulu'],
];
